const Jcategory = [
    {
        index: 0,
        image: "../images/google.png",
        title: "Web Developer",
        rate: "$900-1200/m",
        av: "Full Time",
        companyName: "Google",
        location: "USA",
        vacancy: "01",
        hours: "50h / Week",
        description: "We are seeking a skilled and detail-oriented Web Developer to join our team. The ideal candidate will be responsible for designing, coding, and maintaining websites and web applications that are visually appealing, responsive, and user-friendly. You will collaborate with designers, back-end developers, and other team members to deliver high-quality web solutions.",
        workplace: "-Work from Home",
        education: "-Bachelor degree in any Computer Science Course.",
        experience: "-2 to 5 year(s)",
    },

    {
        index: 1,
        image: "../images/uber.png",
        title: "Freelancer",
        rate: "$1200-1500/m",
        av: "Part Time",
        companyName: "Uber",
        location: "India",
        vacancy: "03",
        hours: "30h / Week",
        description: "We are looking for a reliable and skilled freelance developer to assist with the creation and delivery of various projects on a contract basis. The ideal candidate will have experience in developing academic, web-based, or software projects and be able to work independently while meeting deadlines and quality expectations.",
        workplace: "-Work from Home",
        education: "-Tech & Development degree needed.",
        experience: "-3 to 5 year(s)",
    },

    {
        index: 2,
        image: "../images/linkedin.png",
        title: "Business Associate",
        rate: "$700-900/m",
        av: "Part Time",
        companyName: "Linkedin",
        location: "Germany",
        vacancy: "01",
        hours: "45h / Week",
        description: "We are seeking a motivated and dynamic Business Associate to join our team. The ideal candidate will support various business functions, assist in strategic planning, and help improve operational efficiency across departments. This role is ideal for someone with strong analytical, communication, and problem-solving skills who is eager to grow in a fast-paced business environment.",
        workplace: "-On Site",
        education: "-Commerce degree needed.",
        experience: "-4 to 6 year(s)",
    },

    {
        index: 3,
        image: "../images/facebook.png",
        title: "Digital Marketing",
        rate: "$1000-1200/m",
        av: "Full Time",
        companyName: "Facebook",
        location: "India",
        vacancy: "06",
        hours: "20h / Week",
        description: "We are looking for a creative, data-driven, and results-oriented Digital Marketing Executive to join our marketing team. As a digital marketer, you will be responsible for developing, implementing, and managing online marketing campaigns that promote our brand, products, and services. You will play a major role in enhancing brand awareness within the digital space, driving website traffic, and acquiring leads/customers.",
        workplace: "-On Site",
        education: "-BBA/MBA degree needed.",
        experience: "-1 to 3 year(s)",
    },
];